apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: Create-a-Spring-Boot-app-and-publish-gitlab
  title: Create a Spring Boot app and publish to destination
  description: Create a Spring Boot app and publish to destination repo
  tags:
    - recommended
    - spring-boot
    - java
    - maven
spec:
  owner: nikhil
  system: janus-idp
  type: service
 # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Provide information about the new component
      required:
        - orgName
        - repoName
        - owner
        - componentId
      properties:
        orgName:
          title: Organization Name
          type: string
          default: nikhshar
        repoName:
          title: Repository Name
          type: string
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
        owner:
          title: Owner
          default: nikhshar
          type: string
        componentId:
          title: Name
          type: string
          description: Unique name of the component
    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: gitlab.com
              enum:
                - gitlab.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: nikhshar
              enum:
                - nikhshar
 # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: sourceCodeTemplate
      name: Generating the Source Code Component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}
          owner: nikhshar
          description: ${{ parameters.description }}
          host: ${{ parameters.repo.host }}
          destination: ${{ parameters.repo.owner }}/${{ parameters.componentId }}
          sourceControl: gitlab.com

    - id: publish
      name: Publishing to the Source Code Repository
      action: publish:gitlab
      input:
        allowedHosts: ["${{ parameters.repo.host }}"]
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{ parameters.componentId }}"
        repoVisibility: public
        defaultBranch: main
  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}