apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: Red Hat Developer Hub
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-b@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-b
  description: user{{ index + 1 }} group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-b@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nikhil
spec:
  profile:
    # Intentional no displayName for testing
    email: nikhil@example.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [team-a]
