apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repoName }}
  description: ${{ values.description }}
  annotations:
    argocd/app-name: ${{ values.repoName }}
    backstage.io/kubernetes-id: ${{ values.repoName }}
    gitlab.com/project-slug: ${{ values.orgName }}/${{ values.repoName }}
  tags:
    - java
  links:
    - url: https://devspaces.${{values.cluster}}/#https://${{values.host}}/${{values.destination}}
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: ${{ values.applicationType }}
  lifecycle: production
  owner: ${{ values.owner }}
